### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ivankrauseza** [ivankrauseza/ci-project5b#27]
As a developer, I need to get back to these fixes:

- [ ] Product sorting
- [ ] Order confirmed page - redirect to user orders
- [ ] View order as modal
- [ ] Home page design
